version: '3'

services:
  app:
    image: dfs_app
    container_name: dfs_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: python djangosnippets/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/opt/study/django_full_scale_transcription
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    depends_on:
      - mysqldb
    # tty: true

  mysqldb:
    container_name: dfs_mysqldb
    build:
      context: .
      dockerfile: ./docker/db_mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # root ユーザは接続に使用しないが、指定がないと mysql を起動できない
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - dfs_mysqldb_data:/var/lib/mysql

volumes:
  dfs_mysqldb_data:
